config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  resources :boards, only: %i[index show new create destroy] do
    get "data", on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates_presence_of :generation, :rows, :cols, :data
  validates_numericality_of :generation, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :rows, :cols, only_integer: true, greater_than: 0, less_than_or_equal_to: 100
  validate :data_length_must_match_dimensions

  private

  def data_length_must_match_dimensions
    if data&.length != rows * cols
      errors.add(:data, "length must be equal to rows * cols")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: %i[ show destroy data ]

  MAX_FUTURE_GENERATIONS = 100

  # GET /boards
  def index
    @boards = Board.all
  end

  # GET /boards/1
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # POST /boards
  def create
    gol = GameOfLife.from_file(board_params[:grid_file].tempfile)
    @board = gol.to_board

    if @board.save
      redirect_to @board, notice: "Board was successfully created."
    else
      render :new, status: :unprocessable_entity
    end

  rescue ArgumentError => e
      @board = Board.new
      @board.errors.add(:grid_file, e.message)
      render :new, status: :unprocessable_entity
  end

  # DELETE /boards/1
  def destroy
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to boards_path, status: :see_other, notice: "Board was successfully destroyed." }
    end
  end

  # GET /boards/1/data
  def data
    generation = params[:generation].present? ? params[:generation].to_i : @board.generation
    session_id = params.expect(:session_id)

    # validate session_id
    uuid_regex = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/i
    unless uuid_regex.match?(session_id)
      head :bad_request
      return
    end

    cache_key = "board_#{@board.id}_#{session_id}"

    # generation less than board generation
    if generation < @board.generation
      head :bad_request
      return
    end

    gol_cache = Rails.cache.read(cache_key)

    # generation over the max generation limit
    if (not gol_cache and generation > @board.generation + MAX_FUTURE_GENERATIONS) or
      (gol_cache and gol_cache.generation > gol_cache.generation + MAX_FUTURE_GENERATIONS)
      head :bad_request
      return
    end

    gol = gol_cache && generation > gol_cache.generation ? gol_cache : GameOfLife.new(board: @board)

    while gol.generation < generation
      gol.next_generation
    end

    Rails.cache.write(cache_key, gol, expires_in: 1.hour)
    send_data [ gol.board_data ].pack("B*"), type: "application/octet-stream", disposition: "inline"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def board_params
    params.expect(board: [ :grid_file ])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">

  <form>
  <div class="form-group row">
    <label for="generation" class="col-sm-2 col-form-label">Generation</label>
    <div class="col-sm-10">
      <input type="number" readonly class="form-control" id="generation" value="<%= board.generation %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="rows" class="col-sm-2 col-form-label">Rows</label>
    <div class="col-sm-10">
      <input type="number" readonly class="form-control" id="rows" value="<%= board.rows %>">
    </div>
  </div>
    <div class="form-group row">
      <label for="rows" class="col-sm-2 col-form-label">Cols</label>
      <div class="col-sm-10">
        <input type="number" readonly class="form-control" id="cols" value="<%= board.cols %>">
      </div>
    </div>
</form>

  <%# board.data.scan(/.{#{board.cols}}/).each do |row| %>
<!--    <%#= row.gsub("1", "*").gsub("0", ".") %><br>-->
  <%# end %>

</div>

app/views/boards/_file_form.html.erb
<%= form_for :board, url: boards_path do |form| %>
  <% if board.errors.any? %>
    <div class="alert alert-danger"><%= pluralize(board.errors.count, "error") %> has been found:
      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.file_field :grid_file, accept: "text/plain", required: true %>
  </div>

  <div>
    <%= form.submit class: "btn btn-light fw-bold border-white " %>
  </div>
<% end %>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :generation, style: "display: block" %>
    <%= form.number_field :generation %>
  </div>

  <div>
    <%= form.label :rows, style: "display: block" %>
    <%= form.number_field :rows %>
  </div>

  <div>
    <%= form.label :cols, style: "display: block" %>
    <%= form.number_field :cols %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :data %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/index.html.erb
<% content_for :title, "Boards" %>

<h1>Boards <%= link_to "New board", new_board_path, class: "btn btn-light fw-bold" %></h1>

<div id="boards" class="mt-5">
  <% @boards.each do |board| %>
    <div class="mb-3">
        <%= render board %>
        <div class="mt-1">
          <%= link_to "Show this board", board, class: "btn btn-outline-light fw-bold" %>
        </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<% content_for :title, "New board" %>

<h1 class="mb-2">Create a new board</h1>
<div class="mb-5">
  <p>Upload a board file like the example below:</p>
  <code>
    Generation 3:<br/>
    4 8<br/>
    ........<br/>
    ........<br/>
    ..***...<br/>
    ........<br/>
  </code>
</div>



<%= render "file_form", board: @board %>

<br>
<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<%= render @board %>

<div class="mt-5 mb-5">
  <canvas id="board"
          class="gol-board"
          data-board-id="<%= @board.id %>"
          data-cols="<%= @board.cols %>"
          data-rows="<%= @board.rows %>"
          data-gen="<%= @board.generation %>"
          data-session-id="<%= SecureRandom.uuid %>"
  ></canvas>
</div>

<div class="mb-5">
  <button id="btn-reset" class="btn btn-outline-light fw-bold" style="margin-right: 10px">Reset</button>
  <button id="btn-start" class="btn btn-light fw-bold border-white bg-white">Start</button>
  <button id="btn-stop" class="btn btn-light fw-bold border-white bg-white">Stop</button>
</div>


<div>
  <%= link_to "Back to boards", boards_path %>
</div>
<div class="mt-5">
  <%= button_to "Destroy this board", @board, method: :delete, class: "btn btn-danger fw-bold " %>
</div>

<%= javascript_include_tag "gol" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100" data-bs-theme="dark" lang="en">
  <head>
    <title><%= content_for(:title) || "Gol Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "cover" %>

    <meta name="theme-color" content="#712cf9">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <h3 class="float-md-start mb-0"><a href="/" style="text-decoration: none; color: white">Game of life</a></h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <%= button_to "Logout", destroy_user_session_path, class: "nav-link fw-bold py-1 px-0", method: :delete if user_signed_in? %>
          </nav>
        </div>
      </header>

      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>

      <main class="px-3">

        <%= yield %>

      </main>

      <footer class="mt-auto text-white-50">
        <p>Game of life made by <a href="https://patrix252.dev" class="text-white">@patrix252</a>.</p>
      </footer>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<h1 class="mb-5">Game of life</h1>

<%= link_to "New board", new_board_path, class: 'btn btn-lg btn-light fw-bold border-white bg-white m-2' %>
<%= link_to "Show boards", boards_path, class: 'btn btn-lg btn-outline-light m-2' %>